name: Sinhala Telegram News Bot

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install FFmpeg + Fonts
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            ffmpeg \
            fonts-noto-core \
            fonts-noto-extra \
            fonts-noto-ui-core

          fc-cache -fv

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip

          pip install requests
          pip install beautifulsoup4
          pip install feedparser
          pip install pillow
          pip install moviepy==1.0.3
          pip install imageio
          pip install imageio-ffmpeg
          pip install numpy
          pip install deep-translator
          pip install edge-tts

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python main.py
